
# Build
root: _gh_pages
dest: <%= site.root %>


# Site metadata
brand: Assemble
title: Assemble
lead: The most awe inspiring website in Northern Kentucky.
description: >
  Static site generator for Grunt.js and Yeoman. Assemble makes it dead simple to build modular sites,
  blogs, gh-pages, components and documentation from reusable templates and data.
license:
  type: MIT License
  url: ./license/index.html


# URLs
repo: https://github.com/assemble/assemble
blog: http://assemble.io/blog/
download:
  source: https://github.com/assemble/assemble/archive/master.zip


# SEO/SEM
google:
  analytics: false
  siteid: false


# Comments
disqus:
  shortname: example-assemble-anchors


# Social
social:
  twitter:
    via: doowb
    username: doowb
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
share:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false

